### PR TITLE
[Compose] Add safeMode

### LINKED ISSUE #2452: Lottie JNI Crashes on play store deployed app
We use lottie extensively in our app and it has been crashing intermittently for Android 12 and some devices on production randomly. And we need to solve these crashes. 

Stacktrace -

```
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 29857 >>> packageName <<<

backtrace:
  #00  pc 0x0000000000297f00  /system/lib64/libhwui.so (SkPath::addPath(SkPath const&, SkMatrix const&, SkPath::AddPathMode)+248)
  #01  pc 0x00000000003d498c  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (art_jni_trampoline+124)
```

Another one - 
```
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 5848 >>> packageName <<<

backtrace:
  #00  pc 0x000000000004b750  /apex/com.android.runtime/lib64/bionic/libc.so (__memcpy+96)
  #01  pc 0x00000000002941a8  /system/lib64/libhwui.so (SkPathRef::growForVerbsInPath(SkPathRef const&)+108)
  #02  pc 0x0000000000293834  /system/lib64/libhwui.so (SkPath::addPath(SkPath const&, SkMatrix const&, SkPath::AddPathMode)+168)
  #03  pc 0x00000000003fc04c  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (art_jni_trampoline+124)
```

Another one -

```
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 17199 >>> packageName <<<

backtrace:
  #00  pc 0x000000000029826c  /system/lib64/libhwui.so (SkPath::addPath(SkPath const&, SkMatrix const&, SkPath::AddPathMode)+276)
  #01  pc 0x000000000034dc30  /apex/com.android.art/lib64/libart.so (art_quick_generic_jni_trampoline+144)
  #02  pc 0x0000000002796330  /memfd:jit-zygote-cache
```

**Checklist**

1. Set useSafeMode to true to avoid crashes 
2. Use Logger.setInstance(CustomLogger()) and tried logging on firebase (Not a recommended way to set Logger) 
3. Found another issue for the same one - https://github.com/airbnb/lottie-android/issues/1947

Lottie version - 6.1.0
Android version - 12

**Steps To Reproduce**

Happens intermittently on play store production, but not easily reproducible.

**It can also be related to lottie-compose, as we have that too in our app. Please suggest a way to use the safeModeApi in the compose as well**

### PR DESCRIPTION
**Pull request by kunal-jar**
This allows to use the safeModeApi in LottieAnimation for compose 

Fixes #2452

### CODE REVIEW

File: lottie-compose/src/main/java/com/airbnb/lottie/compose/LottieAnimation.kt [hunk 1]
```diff
@@ -88,6 +90,7 @@ fun LottieAnimation(
     clipTextToBoundingBox: Boolean = false,
     fontMap: Map<String, Typeface>? = null,
     asyncUpdates: AsyncUpdates = AsyncUpdates.AUTOMATIC,
+    isSafeMode: Boolean = false,
```
Comment (gpeal) [inline lottie-compose/src/main/java/com/airbnb/lottie/compose/LottieAnimation.kt:93]:
```suggestion
    safeMode: Boolean = false,
```

Let's remove `is` to be consistent with the other boolean names here.

Comment (kunal-jar) [reply lottie-compose/src/main/java/com/airbnb/lottie/compose/LottieAnimation.kt]: @gpeal done
