### PR TITLE
Prevent a crash on older versions of Android

### LINKED ISSUE #1143: NullPointerException on android 4.3
I got the `NullPointerException` when upgrade lottie to version `3.0.0beta2`. It works on android 8,9 but not 4.3, 5 ( I don't have other devices to test)
Here is my view:
```
<com.airbnb.lottie.LottieAnimationView
        android:id="@+id/lottieView"
        app:lottie_autoPlay="true"
        app:lottie_loop="true"
        app:lottie_scale="0.2"
        app:lottie_rawRes="@raw/ring"
        android:layout_gravity="center"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content" />
```
The json animation file is downloaded from here https://lottiefiles.com/222-trail-loading
And the crash log:

```
Caused by java.lang.NullPointerException
       at com.airbnb.lottie.LottieAnimationView.isAnimating(SourceFile:607)
       at com.airbnb.lottie.LottieAnimationView.onVisibilityChanged(SourceFile:240)
       at android.view.View.dispatchVisibilityChanged(View.java:7628)
       at android.view.View.setFlags(View.java:8632)
       at android.view.View.(View.java:3732)
       at android.widget.ImageView.(ImageView.java:121)
       at androidx.appcompat.widget.AppCompatImageView.(SourceFile:3)
       at com.airbnb.lottie.LottieAnimationView.androidx.appcompat.widget.AppCompatImageView.<init>(SourceFile:91)
       at java.lang.reflect.Constructor.constructNative(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
       at android.view.LayoutInflater.createView(LayoutInflater.java:594)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
       at com.zd.ad.ui.widgets.PhotoPagerAdapter.instantiateItem(SourceFile:28)
       at androidx.viewpager.widget.ViewPager.addNewItem(SourceFile:1010)
       at androidx.viewpager.widget.ViewPager.populate(SourceFile:1158)
       at androidx.viewpager.widget.ViewPager.populate(SourceFile:1092)
       at androidx.viewpager.widget.ViewPager.onMeasure(SourceFile:1622)
       at android.view.View.measure(View.java:15848)
       at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(SourceFile:1699)
       at android.view.View.measure(View.java:15848)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5012)
       at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasureChild(SourceFile:743)
       at com.google.android.material.appbar.HeaderScrollingViewBehavior.findFirstDependency(SourceFile:101)
       at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasure(SourceFile:813)
       at android.view.View.measure(View.java:15848)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5012)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
       at androidx.appcompat.widget.ContentFrameLayout.onMeasure(SourceFile:143)
       at android.view.View.measure(View.java:15848)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5012)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
       at android.view.View.measure(View.java:15848)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5012)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
       at android.view.View.measure(View.java:15848)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5012)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
       at android.view.View.measure(View.java:15848)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5012)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2189)
       at android.view.View.measure(View.java:15848)
       at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:1905)
       at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1104)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1284)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1004)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5481)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:749)
       at android.view.Choreographer.doCallbacks(Choreographer.java:562)
       at android.view.Choreographer.doFrame(Choreographer.java:532)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:735)
       at android.os.Handler.handleCallback(Handler.java:730)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:5103)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:525)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

I wonder could the problem is that lottieview is in viewpager item? Because it works well on other screen without viewpager.

### PR DESCRIPTION
**Pull request by gpeal**
Fixes #1143

### CODE REVIEW

File: lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java [hunk 1]
```diff
@@ -232,6 +232,12 @@ private void init(@Nullable AttributeSet attrs) {
 
   @Override
   protected void onVisibilityChanged(@NonNull View changedView, int visibility) {
+    // This can happen on older versions of Android because onVisibilityChanged gets called from the
+    // constructor or View so this will get called before lottieDrawable gets initialized.
```
Comment (digitalbuddha) [inline lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java]: of View

**Comment by gpeal** [comment]
**[Snapshots Failed](https://app.bitrise.io/build/5ba0a25fb013343e)**

**Comment by gpeal** [comment]
**Snapshot Tests**
**28**: [Report](https://happo.io/a/27/report/5220247ae3235edea4bb425bfbef6f6b7737bb3c-android28) [Diff](https://happo.io/a/27/p/27/compare/master-android28/5220247ae3235edea4bb425bfbef6f6b7737bb3c-android28)
